/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/auth'
import { Route as IndexImport } from './routes/index'
import { Route as HomeTabIdImport } from './routes/home/$tabId'
import { Route as HomeNewChatIndexImport } from './routes/home/newChat/index'
import { Route as HomeNewChatMakeCharacterImport } from './routes/home/newChat/makeCharacter'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HomeTabIdRoute = HomeTabIdImport.update({
  id: '/home/$tabId',
  path: '/home/$tabId',
  getParentRoute: () => rootRoute,
} as any)

const HomeNewChatIndexRoute = HomeNewChatIndexImport.update({
  id: '/home/newChat/',
  path: '/home/newChat/',
  getParentRoute: () => rootRoute,
} as any)

const HomeNewChatMakeCharacterRoute = HomeNewChatMakeCharacterImport.update({
  id: '/home/newChat/makeCharacter',
  path: '/home/newChat/makeCharacter',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/home/$tabId': {
      id: '/home/$tabId'
      path: '/home/$tabId'
      fullPath: '/home/$tabId'
      preLoaderRoute: typeof HomeTabIdImport
      parentRoute: typeof rootRoute
    }
    '/home/newChat/makeCharacter': {
      id: '/home/newChat/makeCharacter'
      path: '/home/newChat/makeCharacter'
      fullPath: '/home/newChat/makeCharacter'
      preLoaderRoute: typeof HomeNewChatMakeCharacterImport
      parentRoute: typeof rootRoute
    }
    '/home/newChat/': {
      id: '/home/newChat/'
      path: '/home/newChat'
      fullPath: '/home/newChat'
      preLoaderRoute: typeof HomeNewChatIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home/$tabId': typeof HomeTabIdRoute
  '/home/newChat/makeCharacter': typeof HomeNewChatMakeCharacterRoute
  '/home/newChat': typeof HomeNewChatIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home/$tabId': typeof HomeTabIdRoute
  '/home/newChat/makeCharacter': typeof HomeNewChatMakeCharacterRoute
  '/home/newChat': typeof HomeNewChatIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home/$tabId': typeof HomeTabIdRoute
  '/home/newChat/makeCharacter': typeof HomeNewChatMakeCharacterRoute
  '/home/newChat/': typeof HomeNewChatIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/home/$tabId'
    | '/home/newChat/makeCharacter'
    | '/home/newChat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home/$tabId'
    | '/home/newChat/makeCharacter'
    | '/home/newChat'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/home/$tabId'
    | '/home/newChat/makeCharacter'
    | '/home/newChat/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  HomeTabIdRoute: typeof HomeTabIdRoute
  HomeNewChatMakeCharacterRoute: typeof HomeNewChatMakeCharacterRoute
  HomeNewChatIndexRoute: typeof HomeNewChatIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  HomeTabIdRoute: HomeTabIdRoute,
  HomeNewChatMakeCharacterRoute: HomeNewChatMakeCharacterRoute,
  HomeNewChatIndexRoute: HomeNewChatIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth",
        "/home/$tabId",
        "/home/newChat/makeCharacter",
        "/home/newChat/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth": {
      "filePath": "auth.tsx"
    },
    "/home/$tabId": {
      "filePath": "home/$tabId.tsx"
    },
    "/home/newChat/makeCharacter": {
      "filePath": "home/newChat/makeCharacter.tsx"
    },
    "/home/newChat/": {
      "filePath": "home/newChat/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
